# Generated by Django 5.2 on 2025-04-15 20:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niab_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fr', models.CharField(max_length=255)),
                ('titre_original', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('annee_sortie', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('PEGI', models.CharField(max_length=50)),
                ('duree', models.DurationField()),
                ('duree_minutes', models.FloatField()),
                ('entrees_totales', models.IntegerField(blank=True, null=True)),
                ('entrees_hebdomadaires', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('recettes_box_office', models.BigIntegerField(blank=True, null=True)),
                ('benefice', models.BigIntegerField(blank=True, null=True)),
                ('rentabilite', models.CharField(blank=True, max_length=50, null=True)),
                ('entrees_prevues', models.IntegerField(blank=True, null=True)),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('url_miniature', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.IntegerField(choices=[(1, 'Salle 1 (120 places)'), (2, 'Salle 2 (80 places)')])),
                ('semaine_debutant', models.DateField()),
                ('audience_quotidienne_estimee', models.IntegerField()),
                ('audience_quotidienne_reelle', models.IntegerField(blank=True, null=True)),
                ('prix_par_billet', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niab_app.film')),
            ],
        ),
        migrations.CreateModel(
            name='RapportHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debutant', models.DateField(unique=True)),
                ('revenus_totaux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couts_totaux', models.DecimalField(decimal_places=2, default=4900.0, max_digits=10)),
                ('taux_occupation', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precision_prediction', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='est_manager',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff_member',
            new_name='est_membre_personnel',
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
        migrations.AddConstraint(
            model_name='projection',
            constraint=models.UniqueConstraint(fields=('numero_salle', 'semaine_debutant'), name='unique_screening_room_week'),
        ),
    ]
